### PR TITLE
Initial work on EU Certificate page.

### LINKED ISSUE #16: DOC | EU Catch Certificate
## 📖 Document

Add in some documentation that covers the EU Catch Certificate and how that will work.

### PR DESCRIPTION
**Pull request by DuckScapePhilip**
I added in the initial work to the EU Certificate page. I added in some recommended EPCIS extensions as well as a grid that shows a list of the KDEs required by the EU Regulations and some descriptions on where those KDEs can be pulled from.

## 🎉 Issues resolved:

- closes #16

### CODE REVIEW

**Comment by DuckScapePhilip** [comment]
Before merging this we still need to:

1. Update the EU Certification guide for the Fishing Gear Type categories. The regulations have specific values they are looking for.

2. Update the EU Certification guide for the Fish Presentation Forms. The regulations have specific values they are looking for.

3. Finish the Conservation Reference Size in the EU Certification guide.

**Comment by IFTGFTC** [comment]
To investigate further with WWF Austria/Switzerland/France on country specific requirements for eCDT.

**Comment by DuckScapePhilip** [comment]
Although I have finished, I did send out some questions to Thomas and GS1. I think we should wait to get those questions answered before we merge this pull request.

**Comment by IFTGFTC** [comment]
Country to country regulations can differ; looking forward to contributions on country specific implementation and electronic requirements.

**Pull request merged**
